rental/urls.py
from django.urls import path, include 
from . import views

import rest_registration

app_name = 'rental'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('cars/', views.CarListView.as_view(), name='car-list'),
    path('car/<uuid:pk>', views.CarDetailView.as_view(), name='car-detail'),
    path('bookings/', views.BookingListView.as_view(), name='booking-list'),
    path('booking/<uuid:pk>', views.BookingDetailView.as_view(), name='booking-detail'),
    path('booking/create', views.BookingCreate.as_view(), name='booking-create'),
    path('clients/', views.UserListView.as_view(), name='customer-list'),
    path('client/<uuid:pk>', views.UserDetailView.as_view(), name='user-detail'),    
    path('Estates/', views.GeneralListView.as_view(), name='general-list'),
]

serval/urls.py
from django.contrib import admin
from django.urls import path, include
import rest_framework
from django.views.generic import RedirectView

import rest_registration

from accounts.views import customers, owners 

urlpatterns = [
    path('', RedirectView.as_view(url='rentals', permanent=True)),
    path('admin/', admin.site.urls),
    path('rentals/', include('rental.urls')),
    path('accounts/', include('rest_registration.api.urls')),
    path('accounts/signup/customer', customers.CustomerSignUpView.as_view(), name='customer_signup'),
    path('accounts/signup/customer', owners.OwnerSignUpView.as_view(), name='owner_signup'),
]

rental/models.py
import datetime 
import uuid

from django.core.validators import MaxValueValidator
from django.db import models
from django.urls.base import reverse

from accounts.models import CustomUser

from django.utils import timezone

from django.utils.translation import gettext_lazy as _


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    def __str__(self):
        return self.name 


class CarModel(models.Model):
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, null=True, verbose_name="model")

    def __str__(self):
        #str() is a temporary addition to solve admin CarModel page error (For some reason, self.name returns 'None') on the main page alone. 
        return str(self.name) 

    
class Insurance(models.Model):
    provider = models.CharField(max_length=100, help_text="Current insurance provider", verbose_name="Insurance Provider", blank=True)
    
    COVERAGE_TYPE = (
        ('c', 'Comprehensive'),
        ('t', 'Third Party'),
        ('n', 'None'),
    )

    coverage = models.CharField(
        max_length=1,
        choices=COVERAGE_TYPE,
        blank=True,
        default='c',
        help_text='Insurance coverage type'
    )

    def __str__(self):
        return self.provider

    class Meta:
        verbose_name = _("insurance provider")
        verbose_name_plural = _("insurance providers")
    

# Change the name of this model to "category". 
class Category(models.Model):
    """Model representing class of car. (Saloon, Estate, Pickup, Medium 4x4, Large 4x4 etc...)"""

    CATEGORY_CHOICES = (
        ('sm','Saloon/Estate'),
        ('md','Medium 4x4'),
        ('lg','Large 4x4'),
        ('sf', 'Safari'),
        ('pu','Pickup'),
        ('xl','Bus/Van'),
    )

    name = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        blank=True,
        default='sm'
    )

    def __str__(self):
        return self.get_name_display()

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')
    

class Car(models.Model):
    """Model representing individual car in database."""
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True)
    model = models.ForeignKey(CarModel, on_delete=models.SET_NULL, null=True)
    # Model year. Validator ensures that no model year  can be set in the future. 
    year = models.IntegerField(validators=[MaxValueValidator(int(datetime.date.today().year) + 1)], null=True, default=2022)
    engine_size = models.IntegerField(default=2500, help_text="Engine size in cc (e.g. 2500, 1600)")
    license_plate = models.CharField(max_length=8, default="KBD 001A")
    color = models.CharField(max_length=50, blank=True, null=True, default='White')
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, related_name="owner")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    
    SEATING_OPTIONS = (
        ('5', 'Five'),
        ('7', 'Seven'),
        ('8', 'Eight'),
        ('9', 'Nine'),
        ('8', 'Eight'),
        ('25', 'Twenty-Five'),
    )

    seats = models.CharField(choices=SEATING_OPTIONS, max_length=2, blank=True)

    FUEL_OPTIONS = (
        ('p', 'Petrol'),
        ('d', 'Diesel'),
    )

    fuel = models.CharField(
        max_length=1,
        choices=FUEL_OPTIONS,
        blank=True,
        default='p',
    )

    DRIVETRAIN_OPTIONS = (
        ('AWD', 'All Wheel Drive'),
        ('FWD', 'Front Wheel Drive'),
        ('RWD', 'Rear Wheel Drive'),
    )

    drivetrain = models.CharField(
        max_length=4,
        choices = DRIVETRAIN_OPTIONS,
        blank=True,
        default='RWD',
    )

    TRANSMISSION_OPTIONS = (
        ('AT', 'Automatic'),
        ('MT', 'Manual'),
    )
        
    transmission = models.CharField(
        max_length=4,
        choices=TRANSMISSION_OPTIONS,
        blank=True,
        default='AT'
    )

    STATUS_CHOICES = (
        ('a', 'Available'),
        ('r', 'Reserved'),
        ('h', 'On Hire'),
        ('m', 'Maintenance'),
    )

    status = models.CharField(
        max_length=1,
        choices = STATUS_CHOICES,
        default='a',
    )

    # Fields for individual car in database
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Automatically generated unique ID. Do not change.")
    mileage = models.IntegerField(null=True)
    
    insurance = models.ForeignKey(Insurance, on_delete=models.RESTRICT, null=True, verbose_name='current insurance provider')
    insurance_expiry_date = models.DateField(null=True, blank=True)

    daily_rate = models.IntegerField(default=3500, help_text="Daily rate in Kenyan Shillings")

    def __str__(self):
        return f'{ self.manufacturer } { self.model }'

    @property
    def insurance_expired(self):
        """Determines if insurance is expired based on due date and current date."""
        return bool(self.insurance_expiry_date and datetime.date.today() > self.insurance_expiry_date)

    class Meta:
        ordering = []
        permissions = (("can_change_availability", "Set car as rented"),)

    def get_absolute_url(self):
        return reverse('rental:car-detail', args=[str(self.id)])

    def __unicode__(self):
        return f'{ self.manufacturer } { self.model }'
        

# Rename to 'hire' to better distinguish between booking, hiring, and invoicing.
class Booking(models.Model):
    """Stores the bookings, for example when it was made, the booking date, and the car ID."""

    # Unique ID for this booking.
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Automatically generated unique ID. Do not change.")
    created_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    car = models.ForeignKey(Car, on_delete=models.SET_NULL, null=True)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(null=True)

    delivery = models.BooleanField(blank=True, null=True)
    chauffer_driven = models.BooleanField(blank=True, null=True)
    
    STATUS_CHOICES = (
        ('p', 'Pending'),
        ('i', 'In Progress'),
        ('c', 'Complete'),
    )

    booking_status = models.CharField(choices=STATUS_CHOICES, default='i', max_length=1)

    @property
    def get_total_days(self):
        """Subtracts start_date from end_date and returns the # days as integer."""
        return (self.end_date - self.start_date).days

    @property
    def get_total_cost(self):
        """Calculates total cost of order by multiplying total days by daily rate of car."""
        total = 0
        days = self.get_total_days

        total = self.get_total_days * self.car.daily_rate

        
        if self.chauffer_driven == True:
            total += (2000 * days)

        if self.delivery == True:
            total += 1,000
        
        return total

    def __str__(self):
        return f'{ self.created_by } | { self.car } | ( {self.start_date} - { self.end_date })'

    def get_absolute_url(self):
        return reverse('rental:booking-detail', args=[str(self.id)])

class Invoice(models.Model):
    id = id = models.AutoField(primary_key=True)

    STATUS_CHOICES = (
        ('p', 'Pending'),
        ('c', 'Cleared'),
        ('e', 'Expired'),
        ('s', 'Success'),
    )

    created = models.DateTimeField(default=timezone.now, blank=True)
    due = models.DateField(blank=True)
    
    status = models.CharField(choices=STATUS_CHOICES, max_length=1, blank=True)


class Payment(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.SET_NULL, null=True)
    invoice = models.ForeignKey(Invoice, on_delete=models.SET_NULL, null=True)

rental/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from . import models


# class PlaceOrderForm(forms.Form):
#     """Initial order forms for customers."""
#     start_date = forms.DateField(help_text='When do you want the car?')
#     end_date = forms.DateField(help_text='When will you return the car?')

#     def clean_data(self, date):
#         data = self.cleaned_data(date)

#         # Check that start date is not in the past
#         if data < datetime.date.today():
#             raise ValidationError(_('Invalid date: Start in past.'))

#         # Ensure that start date is not today (to avoid last_minute bookings.)
#         if data == datetime.date.today():
#             raise ValidationError(_('Invalid date: Please reserve your car at least 24 hours in advance.'))

#         return data

#     cleaned_start_date = clean_data(start_date)
#     cleaned_end_date = clean_data(end_date)
    

rental/views.py
import datetime

from rest_framework import generics, viewsets
from rest_framework.decorators import api_view
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.views import APIView 
from accounts.models import CustomUser
from .models import Booking, Car
from .serializers import BookingSerializer, CarSerializer, UserSerializer

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from django.shortcuts import render, get_object_or_404

from . import forms

from rest_framework import permissions
from .permissions import IsOwnerOrReadOnly 


@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'cars': reverse('car-list', request=request, format=format),
    })    


class IndexView(APIView):
    """Website homepage. Currently simple, only showing number of Cars and Customers in database."""
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'index.html'

    def get(self, request):    
        num_cars = Car.objects.all().count()
        num_users = CustomUser.objects.all().count()
        num_bookings = Booking.objects.all().count()

        return Response({
            'num_cars': num_cars,
            'num_users': num_users,
            'num_bookings': num_bookings,
        })


class CarListView(generics.ListCreateAPIView):
    """Displays all the cars in the database"""
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'car-list.html'

    def get(self, request):
        car_list = Car.objects.all()
        serializer_class = CarSerializer

        return Response({
            'car_list': car_list,
        })


class CarDetailView(DetailView):
    """Displays all information about a specific car."""
    model = Car
    template_name = 'car-detail.html'


class BookingListView(generics.ListCreateAPIView):
    """Showcases all the bookings in the system."""
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'booking-list.html'
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def get(self, request):
        booking_list = Booking.objects.all()
        serializer_class = BookingSerializer

        return Response({
            'booking_list': booking_list,
        })


class BookingDetailView(DetailView):
    """Information about a specific booking made in the system."""
    model = Booking
    template_name = 'booking-detail.html'
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]


permission_classes = [permissions.IsAuthenticated]
class BookingCreate(CreateView):
    model = Booking
    fields = ['car', 'start_date', 'end_date']


    def form_valid(self, form):
        form.instance.created_by = CustomUser.objects.get(pk=self.request.user.pk)
        # form.instance.created_by = self.request.user
        # form.instance.created_by = Booking.objects.get(created_by=self.request.user).user
        return super().form_valid(form)


class BookingUpdate(UpdateView):
    model = Booking
    fields = ['start_date', 'end_date']


class UserListView(generics.ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'user-list.html'

    def get(self, request):
        queryset = CustomUser.objects.all()
        serializer_class = UserSerializer

        return Response({
            'customer_list': queryset,
        })

    def perform_create(self, serializer):
        serializer.save(client=self.request.user)
        

class UserDetailView(DetailView):
    model = CustomUser
    template_name = 'user-detail.html'

    """
    # form.instance.user = self.request.user
    # form.instance.user = Booking.objects.get(user=self.request.user)
    # form.instance.user = Booking.objects.get(user=self.request.user).user 
    # form.instance.user=get_object_or_404(Booking,user=self.request.user).user 
    """

class GeneralListView(ListView):
    model = Car
    template_name = 'cars_by_category.html'

    def get_queryset(self):
        return Car.objects.filter(category__name='sm').filter(status='a')

rental/templates/rental/booking-detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>View booking</h1>
  <p><strong>Car:</strong> {{ booking.car.manufacturer }} {{ booking.car.model }}</p>
  <p><strong>Registration:</strong> {{ booking.car.license_plate }}</p>
  <p><strong>Created By:</strong> {{ booking.created_by }}</p>
  <p><strong>Date Borrowed:</strong> {{ booking.start_date }}</p>
  <p><strong>Due Date:</strong> {{ booking.end_date }}</p>
  <p><strong>Duration:</strong> {{ booking.get_total_days }} days</p>
  <p><strong>Total:</strong> Kshs. {{ booking.get_total_cost }}</p>
  <p><strong>ID:</strong> {{ booking.id }}</p>
  <p></p>
{% endblock %}

rental/templates/rental/booking-list.html
{% extends 'base.html' %}

{% block content %}
    <ul>
        {% if booking_list %}
            {% for booking in booking_list %}
                <li><a href="{{ booking.get_absolute_url }}">{{ booking.client }} ({{ booking.start_date }} - {{ booking.end_date }})</a></li>
            {% endfor %}
        {% else %}
            <p>There are no bookings in the database.</p>
        {% endif %}
    </ul>
{% endblock %}

rental/templates/rental/booking_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Choose your car and dates.</h1>
    <p>Borrower: {{ request.user }}</p>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit">
        </form>
{% endblock %}

rental/templates/rental/car-detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ car.year }} {{ car.manufacturer }} {{ car.model }}</h1>
    <p><strong>Owner:</strong> {{ car.owner }}</p>
    <p><strong>Color:</strong> {{ car.color }}</p>
    <p><strong>License Plate:</strong> {{ car.license_plate }}</p>
    <p><strong>Daily Rate:</strong> Kshs. {{ car.daily_rate }}</p>
    <a href="">Reserve/Hire</a>
    <hr>
    <h3>Insurance Information</h3> 
    <p><strong>Provider: </strong>{{ car.insurance }}</p>
    <p {% if insurance_expired %}class="text-warning"{% endif %}><strong>Expiry Date: </strong>{{ car.insurance_expiry_date }}</p>
    <ul>

    {% for booking in car.booking_set.all %}
        <hr>
        <h3>{{ booking.created_by }}</h3>
        <li><strong>Start: </strong> {{ booking.start_date }}</li>
        <li><strong>End: </strong>{{ booking.end_date }}</li>
        <hr>
    {% endfor %}


{% endblock %}

rental/templates/rental/car-list.html
{% extends 'base.html' %}

{% block content %}
    <h2>All Cars</h2>
    <ul>
        {% for car in car_list %}
            <li><a href="{{ car.get_absolute_url }}">{{ car.manufacturer }} {{ car.model }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

rental/templates/rental/cars_by_category.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ category.name }}</h1>
    <div class="container">
        <ul>
            {% for car in car_list %}
                <li><a href="{{ car.get_absolute_url }}">{{ car.manufacturer }} {{ car.model }} {{ car.daily_rate }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

rental/templates/rental/customer-detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ customer.user.first_name}} {{ customer.user.last_name}}</h1>
{% endblock %}

rental/templates/rental/customer-list.html
{% extends 'base.html' %}

{% block content %}
    <ul>
        {% if customer_list %}
            {% for customer in customer_list %}
                <li><a href="{{ customer.get_absolute_url }}">{{ customer.user.first_name }}</a></li>
            {% endfor %}
        {% else %}
            <p>There are no customers in the database.</p>
        {% endif %}
    </ul>
{% endblock %}