rental/urls.py
from django.urls import path, include 
from . import views

import rest_registration

app_name = 'rental'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('cars/', views.CarListView.as_view(), name='car-list'),
    path('car/<uuid:pk>', views.CarDetailView.as_view(), name='car-detail'),
    path('bookings/', views.BookingListView.as_view(), name='booking-list'),
    path('booking/<uuid:pk>', views.BookingDetailView.as_view(), name='booking-detail'),
    path('booking/create', views.BookingCreate.as_view(), name='booking-create'),
    path('clients/', views.UserListView.as_view(), name='customer-list'),
    path('client/<uuid:pk>', views.UserDetailView.as_view(), name='user-detail'),    
    path('Estates/', views.GeneralListView.as_view(), name='general-list'),
]

serval/urls.py
from django.contrib import admin
from django.urls import path, include
import rest_framework
from django.views.generic import RedirectView

import rest_registration

from accounts.views import customers, owners 

urlpatterns = [
    path('', RedirectView.as_view(url='rentals', permanent=True)),
    path('admin/', admin.site.urls),
    path('rentals/', include('rental.urls')),
    path('accounts/', include('rest_registration.api.urls')),
    path('accounts/signup/customer', customers.CustomerSignUpView.as_view(), name='customer_signup'),
    path('accounts/signup/customer', owners.OwnerSignUpView.as_view(), name='owner_signup'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}<title>SERVAL</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">        
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    {% block links %}{% endblock %} 
  </head>

  <body>
    <header>
      {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light navbar-inverse shadow-sm mb-2 bg-white">
          <div class="container-fluid">
            <a href="{% url 'rental:index' %}" class="navbar-brand logo">Serval</a>
            {% if user.is_authenticated %}
            <div class="account-info ms-auto">
              <a href="#">{{ user.first_name }}</a>
              <a href="{% url 'rest_registration:logout' %}?next={% url 'rental:index' %}">Logout</a>
            </div>
            {% else %}
              <a href="{% url 'rest_registration:login' %}" class="nav-item">Login</a>
            {% endif %}
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
              aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>  
        </nav>
      {% endblock %}
      {% block header %}{% endblock %}
    </header>
    <div class="container">
      <div class="content">
        {% block content %} {% endblock %}
      </div>
    </div>
    {% block scripts %} {% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

<head>
    {% block title %}<title>Serval - Home</title>{% endblock %}
</head>

{% block content %}
    <h1>Homepage</h1>
    <div class="container">
        <div class="centered">
            <ul><a href="{% url 'rental:booking-list' %}">View all Bookings</a></ul>
            <ul><a href="{% url 'rental:car-list' %}">View all Cars</a></ul>
            <ul>Total Cars: {{ num_cars }}</ul>
            <ul>Total Users: {{ num_users }}</ul>
            <ul>Total Bookings: {{ num_bookings }}</ul>
            <h2>Categories</h2>
            <a href="{% url 'rental:general-list' %}">General</a>
            <a href="">Medium</a>
            <a href="">SUV</a>
            <a href="">Pickup</a>
            <a href="">Safari</a>
            <a href="">Bus</a>
        </div>
    </div>
    
{% endblock %}